### PR TITLE
Marking `go` as a dependency 

### PR DESCRIPTION
**Pull request by tusqasi**
Makes it easier to follow along the readme

### CODE REVIEW

**Comment by tusqasi** [comment]
Sorry if i am spamming PRs, but kinda don't know how this works.
Let me know if i messed something up.

**Comment by lemnos** [comment]
No, I am just horrible at responding to PRs :P. My apologies. This looks fine, but can you remove the apt command or add a comment suggesting it is debian specific?

**Comment by tusqasi** [comment]
How about now?

**Comment by lemnos** [comment]
Sorry for the prolonged response. This looks fine, but can you squash these into a single commit? It helps keep the history clean.

**Comment by tusqasi** [comment]
Is this correct? I don't exactly know if that was correctly done.  
Hope that was fine  
😅

**Comment by lemnos** [comment]
The goal is to have a single commit. There are currently still three separate ones. You can use `git rebase -i` to squash the commits of interest. You might find [this](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) useful.

**Comment by lemnos** [comment]
I've gone ahead and merged this anyway. Just in time for 2022 ;). 

Happy new year.

**Pull request merged**
